**Python lists vs. Numpy arrays** 

In [20]:
# sourcery skip: aug-assign
"""
Background: in most common programming languages, arrays are the go-to for data 
structures. However, Python does not have arrays pre-built into the language
and lists take on that role. This means that numpy arrays must be used instead. 
The major difference is that numpy arrays support mathematical operations while 
python lists, do not. Python lists behave more as generic object types. 
"""

import numpy as np 

# create a python list and numpy array with the same data
pythonlist = [1,2,3]
numpyarray = np.array([1,2,3])

# print python list as normal 
for element in pythonlist:
    print(element)

# print numpy array
for element in numpyarray:
    print(element)

#! Both behave as expected when iterating through a for loop 
#! Now let's append both data types 

# first method for a python list, use the append method
pythonlist.append(4)

# Also can add the number 5 using concatenation
pythonlist = pythonlist + [5]
print(pythonlist)

# When you add a two arrays together in numpy, remember that it is 
# ... in fact an array and will add n to all elements of the matrix
print(numpyarray + np.array([4]))

# Numpy knows to treat an array as scalar if it has only one element,  
# ... otherwise it will assume that it is an array 

# The following lines result in the same array 
print(numpyarray*np.array([2]))
print(numpyarray*2)

#! Remember, using mathematical operations on python objects such as lists
#! ... does not result in math actually being done, ex. this just doubles the list
# For python lists, the multiplication does repitions, for numpyarrays, it does
# ... multiplication as you would expect 
print(pythonlist*2)

# One of the benefits of a np.array() is that it supports elementwise operations using
# ...mathematical functions: 
print(np.sin(numpyarray))
 

1
2
3
1
2
3
[1, 2, 3, 4, 5]
[5 6 7]
[2 4 6]
[2 4 6]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[0.84147098 0.90929743 0.14112001]


**The Dot Product** 

In [25]:
# sourcery skip: sum-comprehension
import numpy as np 

# Remember that the dot product between two vectors tracks how similar in direction 
# ... their final product is pointing. This can be calculated by finding the sum of x-products 
# .... and the sum of y-products. 
a = np.array([1,2])
b = np.array([3, 4])

# Remember the iterator in python for loops is always initialized at zero
# If the array has two columns, they will be indexed as 0, 1
# In this case, i is iterating from zero to one 
# Calculate the dot product
dot = 0
for i in range(len(a)):
    dot += a[i]*b[i]
print(dot)

# Or just use the dot function in numpy 
print(np.dot(a,b))

# Find the magnitude of a vector
np.sqrt((a**2).sum())

# Or use the linalg module from numpy
np.linalg.norm(a)

#! Using numpy to calculate the dot product is much faster than using for loops 
#! ... however keep in mind there are scenarios where this is not always possible 


11
11
