**Python lists vs. Numpy arrays** 

In [19]:
"""
Background: in most common programming languages, arrays are the go-to for data 
structures. However, Python does not have arrays pre-built into the language
and lists take on that role. This means that numpy arrays must be used instead. 
The major difference is that numpy arrays support mathematical operations while 
python lists, do not. Python lists behave more as generic object types. 
"""

import numpy as np 

# create a python list and numpy array with the same data
pythonlist = [1,2,3]
numpyarray = np.array([1,2,3])

# print python list as normal 
for element in pythonlist:
    print(element)

# print numpy array
for element in numpyarray:
    print(element)

#! Both behave as expected when iterating through a for loop 
#! Now let's append both data types 

# first method for a python list, use the append method
pythonlist.append(4)

# Also can add the number 5 using concatenation
pythonlist = pythonlist + [5]
print(pythonlist)

# When you add a two arrays together in numpy, remember that it is 
# ... in fact an array and will add n to all elements of the matrix
print(numpyarray + np.array([4]))

# Numpy knows to treat an array as scalar if it has only one element,  
# ... otherwise it will assume that it is an array 

# The following lines result in the same array 
print(numpyarray*np.array([2]))
print(numpyarray*2)

#! Remember, using mathematical operations on python objects such as lists
#! ... does not result in math actually being done, ex. this just doubles the list
# For python lists, the multiplication does repitions, for numpyarrays, it does
# ... multiplication as you would expect 
print(pythonlist*2)

# One of the benefits of a np.array() is that it supports elementwise operations using
# ...mathematical functions: 
print(np.sin(numpyarray))
 

1
2
3
1
2
3
[1, 2, 3, 4, 5]
[5 6 7]
[2 4 6]
[2 4 6]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[0.84147098 0.90929743 0.14112001]
